Automation of polarian: CEPH-83574831
red-hat-storage/ceph-qe-scripts pull request #384
Opened 2023-02-01 09:34 UTC by ckulal

Signed-off-by: ckulal <ckulal@redhat.com>

2023-02-01 11:10 UTC, viduship submitted a review, later dismissed

2023-02-01 11:25 UTC, hmaheswa requested changes

2023-02-01 11:25 UTC, hmaheswa commented on rgw/v2/tests/s3_swift/configs/test_bucket_remove_with_multipart_abort.yaml
> +     split_size: 5
@ckulal please increase split size and object size

2023-02-01 11:39 UTC, anrao19 approved these changes

2023-02-01 11:45 UTC, hmaheswa approved these changes

2023-02-02 04:31 UTC, udaysk23 approved these changes

2023-02-02 04:43 UTC, TejasC88 approved these changes

2023-02-02 04:43 UTC, merged