integrating lifecycle and/or resharding with notifications
red-hat-storage/ceph-qe-scripts pull request #412
Opened 2023-03-13 14:47 UTC by hmaheswa

2023-03-14 07:55 UTC, viduship requested changes
@hmaheswa , Can the results of rgw/v2/tests/s3_swift/configs/test_bucket_notification_kafka_broker_persistent_manual_reshard.yaml be extrapolated for rgw/v2/tests/s3_swift/configs/test_lc_rule_expiration_manual_reshard_notifications.yaml?

2023-03-17 10:54 UTC, viduship approved these changes

2023-03-17 11:11 UTC, hmaheswa commented
> @hmaheswa , Can the results of rgw/v2/tests/s3_swift/configs/test_bucket_notification_kafka_broker_persistent_manual_reshard.yaml be extrapolated for rgw/v2/tests/s3_swift/configs/test_lc_rule_expiration_manual_reshard_notifications.yaml?

addressed @viduship

2023-03-17 12:45 UTC, anrao19 approved these changes

2023-03-17 13:05 UTC, mkasturi18 approved these changes

2023-03-17 13:06 UTC, merged